config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get  '/register', to: 'users#new'
  get  '/login',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  get  '/logout',   to: 'sessions#destroy'
  get  '/pin',      to: 'sessions#pin'
  post '/pin',      to: 'sessions#pin'

  resources :posts, except: :destroy do
    resources :comments, only: :create do
      member do
        post 'vote'
      end
    end

    member do
      post 'vote'
    end
  end

  resources :categories, only: [:new, :create, :show]
  resources :users,      only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  PER_PAGE = 3

  include Voteable
  include Sluggable

  default_scope { order 'created_at ASC' }

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many   :comments
  has_many   :post_categories
  has_many   :categories, through: :post_categories

  validates :title,       presence: true, length: { minimum: 3 }
  validates :url,         presence: true  #, uniqueness: true
  validates :description, presence: true

  sluggable_column :title
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,                   only:   [:show, :edit, :update, :vote]
  before_action :require_user,               except: [:index, :show]
  before_action :require_admin_or_same_user, only:   [:edit, :update]

  def index
    @posts = Post.all.sort_by { |post| -post.total_votes }

    respond_to do |format|
      format.html
      format.json { render json: @posts }
      format.xml  { render xml: @posts }
    end
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post         = Post.new post_params
    @post.creator = current_user

    if @post.save
      flash[:notice] = 'Post successfully created'
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      flash[:notice] = 'Post has been updated'
      redirect_to posts_path
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @post)

    respond_to do |format|
      format.html do
        if v.valid?
          flash[:notice] = 'Your vote has been counted'
        else
          flash[:error]  = 'Sorry, you can only vote once per item'
        end
        redirect_to :back
      end

      format.js
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slug: params[:id]
  end

  def require_admin_or_same_user
    super(@post.creator)
  end
end

app/views/posts/____pagination.html.erb
<% @pages.times do |n| %>
  <% if (!params[:offset] && n == 0) || params[:offset].to_s == (n * Post::PER_PAGE).to_s  %>
    <%= "#{n == 0 ? '' : '|'} Page #{n + 1}" %>
  <% else %>
    <%= link_to "#{n == 0 ? '' : '|'} Page #{n + 1}", posts_path(offset: n * Post::PER_PAGE) %>
  <% end %>
<% end %>


<!--     # @posts = Post.limit(Post::PER_PAGE).offset(params[:offset])
    # @pages = Post.all.size.fdiv(Post::PER_PAGE).ceil
 -->

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <div class='control-group'>
      <%= f.label      :title %>
      <%= f.text_field :title %>
    </div>
    <div class='control-group'>
      <%= f.label      :url %>
      <%= f.text_field :url %>
    </div>
    <div class='control-group'>
      <%= f.label     :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>
    <div class='control-group'>
      <%= f.label 'Categories' %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <%= cb.label(class: 'checkbox inline') { cb.check_box(class: 'checkbox') + cb.text } %>
      <% end %>
    </div>
    <%= f.submit "#{@post.new_record? ? 'Create' : 'Update'} Post", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %>
      <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
        <i class='icon-arrow-up'></i>
      <% end %>
      <br>
    <% end %>
    <span id='post_<%= post.to_param %>_votes'><%= post.total_votes %> votes</span>
    <% if logged_in? %>
      <br>
      <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
        <i class='icon-arrow-down'></i>
      <% end %>
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span>
      <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= format_time post.created_at %></small>
      <br>
      <span><%= link_to("#{post.comments.size} comments", post_path(post)) %></span>

      <% if logged_in? && (admin? || same_user?(post.creator)) %>
        <span><%= link_to("[edit]", edit_post_path(post)) %></span>
      <% end %>
    </p>
  </div>
</div>

app/views/posts/_post.html.haml
.row
  .span0.well.text-center
    - if logged_in?
      = link_to vote_post_path(post, vote: true), method: 'post', remote: true do
        %i.icon-arrow-up
      %br/
    %span{id: "post_#{post.to_param}_votes"}
      = post.total_votes
      votes
    - if logged_in?
      %br/
      = link_to vote_post_path(post, vote: false), method: 'post', remote: true do
        %i.icon-arrow-down
  .span8.well
    = render post.categories
    %h4= link_to post.title, fix_url(post.url)
    %p= post.description
    %p
      %span.quiet posted by
      = link_to post.creator.username, user_path(post.creator)
      %small
        at #{format_time post.created_at}
      %br/
      %span= link_to("#{post.comments.size} comments", post_path(post))
      - if logged_in? && (admin? || same_user?(post.creator))
        %span= link_to("[edit]", edit_post_path(post))

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this post' %>

<%= render 'form', button_text: 'Update' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>

<%= render partial: 'post', collection: @posts  %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<%= render 'form', button_text: 'Create' %>

app/views/posts/show.html.erb
<% if logged_in? && (admin? || same_user?(@post.creator)) %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<p>
  <%= render @post.categories %>
</p>

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr>

<% if logged_in? %>
  <%= form_for [@post, @comment] do |f| %>
    <%= render 'shared/errors', obj: @comment %>
    <div class='control-group'>
      <%= f.label     :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 3, class: 'span4' %>
    </div>
    <%= f.submit 'Create comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h5>Comments:</h5>

<%= render sort_by_vote(@post.comments.reload) %>

app/views/posts/test.haml
.row
  .span0.well.text-center
    - if logged_in?
      = link_to vote_post_path(post, vote: true), method: 'post', remote: true do
        %i.icon-arrow-up
      %br/
    %span{id: "post_#{post.to_param}_votes"}
      = post.total_votes
      votes
    - if logged_in?
      %br/
      = link_to vote_post_path(post, vote: false), method: 'post', remote: true do
        %i.icon-arrow-down
  .span8.well
    = render post.categories
    %h4= link_to post.title, fix_url(post.url)
    %p= post.description
    %p
      %span.quiet posted by
      = link_to post.creator.username, user_path(post.creator)
      %small
        at #{format_time post.created_at}
      %br/
      %span= link_to("#{post.comments.size} comments", post_path(post))
      - if logged_in? && (admin? || same_user?(post.creator))
        %span= link_to("[edit]", edit_post_path(post))

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%= @post.to_param %>_votes').text('<%= @post.total_votes %> votes')
<% else %>
  alert('You can only vote on a post once')
<% end %>